# bedrock_server_manager/config/bcm_config.py
"""
Manages the core application configuration file (bedrock_server_manager.json).

This module is responsible for handling a simple JSON configuration file that
stores essential startup settings like the data directory and database URL.
It uses the `platformdirs` library to locate the appropriate user-specific
configuration directory in a cross-platform way.

The main components are:
- get_config_dir(): Returns the cross-platform configuration directory path.
- get_config_path(): Returns the path to the config file.
- load_config(): Reads the config file and returns its contents.
- save_config(data): Writes data to the config file.
"""

from __future__ import annotations

import json
import logging
import os
from typing import Any, Dict

from platformdirs import user_config_dir

from .const import CONFIG_FILE_NAME, env_name, package_name

logger = logging.getLogger(__name__)


_custom_config_dir: str | None = None
_custom_data_dir: str | None = None
_custom_log_level: str | None = None
_custom_db_url: str | None = None


def set_custom_config_dir(path: str | None) -> None:
    global _custom_config_dir
    _custom_config_dir = path


def set_custom_data_dir(path: str | None) -> None:
    global _custom_data_dir
    _custom_data_dir = path


def set_custom_db_url(url: str | None) -> None:
    global _custom_db_url
    _custom_db_url = url


def set_custom_log_level(level: str | int | None) -> None:
    global _custom_log_level
    if isinstance(level, int):
        level = logging.getLevelName(level)
    if level:
        _custom_log_level = level.upper()
    else:
        _custom_log_level = None


def get_config_dir() -> str:
    """Returns the cross-platform configuration directory path."""
    if _custom_config_dir:
        return _custom_config_dir
    env_config_dir = os.getenv(f"{env_name}_CONFIG_DIR")
    if env_config_dir:
        return env_config_dir
    return str(user_config_dir(package_name))


def get_config_path() -> str:
    """Returns the full, platform-specific path to the configuration file."""
    return os.path.join(get_config_dir(), CONFIG_FILE_NAME)


def _read_raw_config() -> Dict[str, Any]:
    """Reads the JSON configuration file without applying defaults or overrides."""
    from typing import cast

    config_path = get_config_path()
    if os.path.exists(config_path):
        try:
            with open(config_path, "r", encoding="utf-8") as f:
                return cast(Dict[str, Any], json.load(f))
        except (json.JSONDecodeError, OSError) as e:
            logger.error(f"Failed to load configuration file at {config_path}: {e}")
    return {}


def _resolve_setting(
    name: str,
    cli_val: Any,
    env_var_name: str,
    config: Dict[str, Any],
    config_key: str,
    default_val: Any,
) -> Any:
    """
    Resolves a setting in the order of precedence:
    1. CLI Argument
    2. Environment Variable
    3. Configuration File
    4. Default Value
    """
    if cli_val:
        logger.info(f"Using CLI argument for {name}: {cli_val}")
        return cli_val

    env_val = os.getenv(env_var_name)
    if env_val:
        logger.info(f"Using {env_var_name} environment variable for {name}: {env_val}")
        return env_val

    if config_key in config and config[config_key]:
        return config[config_key]

    logger.info(f"Configuration '{name}' not set. Defaulting to {default_val}.")
    return default_val


def load_config() -> Dict[str, Any]:
    """
    Loads and resolves the configuration settings.
    Configuration values are resolved in the following order of precedence:
    1. CLI Arguments
    2. Environment variables (BSM_DATA_DIR, BSM_DB_URL, BSM_LOG_LEVEL)
    3. Values from the configuration file (`bedrock_server_manager.json`)
    4. Default values generated by the application.

    Returns:
        Dict[str, Any]: The fully resolved configuration data.
    """
    config = _read_raw_config()
    final_config = config.copy()

    config_dir = get_config_dir()
    os.makedirs(config_dir, exist_ok=True)

    final_config["data_dir"] = _resolve_setting(
        name="data_dir",
        cli_val=_custom_data_dir,
        env_var_name=f"{env_name}_DATA_DIR",
        config=config,
        config_key="data_dir",
        default_val=os.path.join(config_dir, "data"),
    )

    final_config["db_url"] = _resolve_setting(
        name="db_url",
        cli_val=_custom_db_url,
        env_var_name=f"{env_name}_DB_URL",
        config=config,
        config_key="db_url",
        default_val=f"sqlite:///{os.path.join(config_dir, f'{package_name}.db')}",
    )

    final_log_level = _resolve_setting(
        name="log_level",
        cli_val=_custom_log_level,
        env_var_name=f"{env_name}_LOG_LEVEL",
        config=config,
        config_key="logging_level",
        default_val="INFO",
    )
    if isinstance(final_log_level, str):
        final_log_level = final_log_level.upper()
    final_config["logging_level"] = final_log_level

    return final_config


def save_config(data: Dict[str, Any]):
    """
    Saves the given data to the JSON configuration file.

    It ensures the configuration directory exists and writes the data
    with an indent for readability.

    Args:
        data (Dict[str, Any]): The configuration data to save.
    """
    try:
        os.makedirs(get_config_dir(), exist_ok=True)
        with open(get_config_path(), "w", encoding="utf-8") as f:
            json.dump(data, f, indent=4)
    except OSError as e:
        logger.error(f"Failed to save configuration file at {get_config_path()}: {e}")


def get_config_value(key: str, default: Any = None) -> Any:
    """
    Retrieves a single value from the configuration file.
    Supports dot notation for nested keys (e.g., 'web.cors_origins').

    Args:
        key (str): The key of the value to retrieve.
        default (Any, optional): The default value to return if the key is not found.

    Returns:
        Any: The configuration value or the default.
    """
    config = load_config()
    keys = key.split(".")
    value = config
    for k in keys:
        if isinstance(value, dict) and k in value:
            value = value[k]
        else:
            return default
    return value


def set_config_value(key: str, value: Any):
    """
    Sets a single value in the configuration file.

    It loads the current raw file, updates the key with the new value,
    and then saves the entire configuration back to the file,
    preserving any values that were previously explicitly set.

    Args:
        key (str): The key of the value to set.
        value (Any): The new value.
    """
    config = _read_raw_config()
    config[key] = value
    save_config(config)
