"""Generated by scripts/generate_plugin_api.py; do not edit manually."""

from typing import Any, AsyncContextManager, Callable, Mapping, Protocol

from bedrock_server_manager.api.models import (
    AddPlayersManuallyRequest,
    AddPlayersManuallyResponse,
    AddServerBanRequest,
    AddServerBanResponse,
    AddToAllowlistRequest,
    AddToAllowlistResponse,
    BackupAllRequest,
    BackupAllResponse,
    BackupConfigFileRequest,
    BackupConfigFileResponse,
    BackupWorldRequest,
    BackupWorldResponse,
    BroadcastRequest,
    BroadcastResponse,
    DisableAddonRequest,
    DisableAddonResponse,
    EnableAddonRequest,
    EnableAddonResponse,
    ExportWorldRequest,
    ExportWorldResponse,
    GetAllGlobalSettingsRequest,
    GetAllGlobalSettingsResponse,
    GetAllKnownPlayersRequest,
    GetAllKnownPlayersResponse,
    GetAllowlistRequest,
    GetAllowlistResponse,
    GetAllServersDataRequest,
    GetAllServersDataResponse,
    GetAllServerSettingsRequest,
    GetAllServerSettingsResponse,
    GetBedrockProcessInfoRequest,
    GetBedrockProcessInfoResponse,
    GetGlobalSettingRequest,
    GetGlobalSettingResponse,
    GetPermissionsRequest,
    GetPermissionsResponse,
    GetPluginSettingRequest,
    GetPluginSettingResponse,
    GetPluginStatusesRequest,
    GetPluginStatusesResponse,
    GetPropertiesRequest,
    GetPropertiesResponse,
    GetServerBansRequest,
    GetServerBansResponse,
    GetServerRunningStatusRequest,
    GetServerRunningStatusResponse,
    GetServerSettingRequest,
    GetServerSettingResponse,
    GetServerSummaryRequest,
    GetServerSummaryResponse,
    GetSystemAndAppInfoRequest,
    GetSystemAndAppInfoResponse,
    GetWorldNameRequest,
    GetWorldNameResponse,
    ImportAddonRequest,
    ImportAddonResponse,
    ImportWorldRequest,
    ImportWorldResponse,
    InstallNewServerRequest,
    InstallNewServerResponse,
    ListAvailableAddonsRequest,
    ListAvailableAddonsResponse,
    ListAvailableWorldsRequest,
    ListAvailableWorldsResponse,
    ListBackupFilesRequest,
    ListBackupFilesResponse,
    ListInstalledAddonsRequest,
    ListInstalledAddonsResponse,
    PruneDownloadCacheRequest,
    PruneDownloadCacheResponse,
    PruneOldBackupsRequest,
    PruneOldBackupsResponse,
    PublishWsEventRequest,
    PublishWsEventResponse,
    ReloadSinglePluginRequest,
    ReloadSinglePluginResponse,
    RemoveFromAllowlistRequest,
    RemoveFromAllowlistResponse,
    ReorderAddonsRequest,
    ReorderAddonsResponse,
    RestartServerRequest,
    RestartServerResponse,
    RestoreAllRequest,
    RestoreAllResponse,
    RestoreConfigFileRequest,
    RestoreConfigFileResponse,
    RestoreWorldRequest,
    RestoreWorldResponse,
    ScanAndUpdatePlayerDbRequest,
    ScanAndUpdatePlayerDbResponse,
    SendCommandRequest,
    SendCommandResponse,
    SendToClientRequest,
    SendToClientResponse,
    SendToUserRequest,
    SendToUserResponse,
    SetCustomGlobalSettingRequest,
    SetCustomGlobalSettingResponse,
    SetPermissionsRequest,
    SetPermissionsResponse,
    SetPluginSettingRequest,
    SetPluginSettingResponse,
    SetPropertiesRequest,
    SetPropertiesResponse,
    SetServerCustomValueRequest,
    SetServerCustomValueResponse,
    SetServerStatusRequest,
    SetServerStatusResponse,
    StartServerRequest,
    StartServerResponse,
    StopServerRequest,
    StopServerResponse,
    UnregisterDataProviderRequest,
    UnregisterDataProviderResponse,
    UpdateServerPlayerStatsRequest,
    UpdateServerPlayerStatsResponse,
    UpdateServerRequest,
    UpdateServerResponse,
    UpdateServerStatusesRequest,
    UpdateServerStatusesResponse,
    ValidatePropertyValueRequest,
    ValidatePropertyValueResponse,
)


class AddonAPI(Protocol):
    async def disable_addon(
        self, request: DisableAddonRequest | Mapping[str, object]
    ) -> DisableAddonResponse: ...

    async def enable_addon(
        self, request: EnableAddonRequest | Mapping[str, object]
    ) -> EnableAddonResponse: ...

    async def import_addon(
        self, request: ImportAddonRequest | Mapping[str, object]
    ) -> ImportAddonResponse: ...

    async def list_available_addons(
        self, request: ListAvailableAddonsRequest | Mapping[str, object]
    ) -> ListAvailableAddonsResponse: ...

    async def list_installed_addons(
        self, request: ListInstalledAddonsRequest | Mapping[str, object]
    ) -> ListInstalledAddonsResponse: ...

    async def reorder_addons(
        self, request: ReorderAddonsRequest | Mapping[str, object]
    ) -> ReorderAddonsResponse: ...


class AllowlistAPI(Protocol):
    async def add_to_allowlist(
        self, request: AddToAllowlistRequest | Mapping[str, object]
    ) -> AddToAllowlistResponse: ...

    async def get_allowlist(
        self, request: GetAllowlistRequest | Mapping[str, object]
    ) -> GetAllowlistResponse: ...

    async def remove_from_allowlist(
        self, request: RemoveFromAllowlistRequest | Mapping[str, object]
    ) -> RemoveFromAllowlistResponse: ...


class ApplicationAPI(Protocol):
    async def get_all_servers_data(
        self, request: GetAllServersDataRequest | Mapping[str, object]
    ) -> GetAllServersDataResponse: ...

    def get_system_and_app_info(
        self, request: GetSystemAndAppInfoRequest | Mapping[str, object]
    ) -> GetSystemAndAppInfoResponse: ...

    async def list_available_worlds(
        self, request: ListAvailableWorldsRequest | Mapping[str, object]
    ) -> ListAvailableWorldsResponse: ...

    async def update_server_statuses(
        self, request: UpdateServerStatusesRequest | Mapping[str, object]
    ) -> UpdateServerStatusesResponse: ...


class BackupRestoreAPI(Protocol):
    async def backup_all(
        self, request: BackupAllRequest | Mapping[str, object]
    ) -> BackupAllResponse: ...

    async def backup_config_file(
        self, request: BackupConfigFileRequest | Mapping[str, object]
    ) -> BackupConfigFileResponse: ...

    async def backup_world(
        self, request: BackupWorldRequest | Mapping[str, object]
    ) -> BackupWorldResponse: ...

    async def list_backup_files(
        self, request: ListBackupFilesRequest | Mapping[str, object]
    ) -> ListBackupFilesResponse: ...

    async def prune_old_backups(
        self, request: PruneOldBackupsRequest | Mapping[str, object]
    ) -> PruneOldBackupsResponse: ...

    async def restore_all(
        self, request: RestoreAllRequest | Mapping[str, object]
    ) -> RestoreAllResponse: ...

    async def restore_config_file(
        self, request: RestoreConfigFileRequest | Mapping[str, object]
    ) -> RestoreConfigFileResponse: ...

    async def restore_world(
        self, request: RestoreWorldRequest | Mapping[str, object]
    ) -> RestoreWorldResponse: ...


class BanAPI(Protocol):
    async def add_server_ban(
        self, request: AddServerBanRequest | Mapping[str, object]
    ) -> AddServerBanResponse: ...

    async def get_server_bans(
        self, request: GetServerBansRequest | Mapping[str, object]
    ) -> GetServerBansResponse: ...


class InstallAPI(Protocol):
    async def install_new_server(
        self, request: InstallNewServerRequest | Mapping[str, object]
    ) -> InstallNewServerResponse: ...

    async def update_server(
        self, request: UpdateServerRequest | Mapping[str, object]
    ) -> UpdateServerResponse: ...


class MiscAPI(Protocol):
    async def prune_download_cache(
        self, request: PruneDownloadCacheRequest | Mapping[str, object]
    ) -> PruneDownloadCacheResponse: ...


class PermissionsAPI(Protocol):
    async def get_permissions(
        self, request: GetPermissionsRequest | Mapping[str, object]
    ) -> GetPermissionsResponse: ...

    async def set_permissions(
        self, request: SetPermissionsRequest | Mapping[str, object]
    ) -> SetPermissionsResponse: ...


class PlayerAPI(Protocol):
    async def add_players_manually(
        self, request: AddPlayersManuallyRequest | Mapping[str, object]
    ) -> AddPlayersManuallyResponse: ...

    async def get_all_known_players(
        self, request: GetAllKnownPlayersRequest | Mapping[str, object]
    ) -> GetAllKnownPlayersResponse: ...

    async def scan_and_update_player_db(
        self, request: ScanAndUpdatePlayerDbRequest | Mapping[str, object]
    ) -> ScanAndUpdatePlayerDbResponse: ...


class PluginsAPI(Protocol):
    async def get_plugin_setting(
        self, request: GetPluginSettingRequest | Mapping[str, object]
    ) -> GetPluginSettingResponse: ...

    async def get_plugin_statuses(
        self, request: GetPluginStatusesRequest | Mapping[str, object]
    ) -> GetPluginStatusesResponse: ...

    async def reload_plugin(
        self, request: ReloadSinglePluginRequest | Mapping[str, object]
    ) -> ReloadSinglePluginResponse: ...

    async def set_plugin_setting(
        self, request: SetPluginSettingRequest | Mapping[str, object]
    ) -> SetPluginSettingResponse: ...


class PropertiesAPI(Protocol):
    async def get_properties(
        self, request: GetPropertiesRequest | Mapping[str, object]
    ) -> GetPropertiesResponse: ...

    async def set_properties(
        self, request: SetPropertiesRequest | Mapping[str, object]
    ) -> SetPropertiesResponse: ...

    def validate_property_value(
        self, request: ValidatePropertyValueRequest | Mapping[str, object]
    ) -> ValidatePropertyValueResponse: ...


class ServerAPI(Protocol):
    async def get_all_settings(
        self, request: GetAllServerSettingsRequest | Mapping[str, object]
    ) -> GetAllServerSettingsResponse: ...

    async def get_setting(
        self, request: GetServerSettingRequest | Mapping[str, object]
    ) -> GetServerSettingResponse: ...

    async def get_summary(
        self, request: GetServerSummaryRequest | Mapping[str, object]
    ) -> GetServerSummaryResponse: ...

    async def restart(
        self, request: RestartServerRequest | Mapping[str, object]
    ) -> RestartServerResponse: ...

    async def send_command(
        self, request: SendCommandRequest | Mapping[str, object]
    ) -> SendCommandResponse: ...

    async def set_custom_value(
        self, request: SetServerCustomValueRequest | Mapping[str, object]
    ) -> SetServerCustomValueResponse: ...

    async def set_status(
        self, request: SetServerStatusRequest | Mapping[str, object]
    ) -> SetServerStatusResponse: ...

    async def start(
        self, request: StartServerRequest | Mapping[str, object]
    ) -> StartServerResponse: ...

    async def stop(
        self, request: StopServerRequest | Mapping[str, object]
    ) -> StopServerResponse: ...

    async def update_player_stats(
        self, request: UpdateServerPlayerStatsRequest | Mapping[str, object]
    ) -> UpdateServerPlayerStatsResponse: ...


class SettingsAPI(Protocol):
    async def get_all_global_settings(
        self, request: GetAllGlobalSettingsRequest | Mapping[str, object]
    ) -> GetAllGlobalSettingsResponse: ...

    async def get_global_setting(
        self, request: GetGlobalSettingRequest | Mapping[str, object]
    ) -> GetGlobalSettingResponse: ...

    async def set_custom_global_setting(
        self, request: SetCustomGlobalSettingRequest | Mapping[str, object]
    ) -> SetCustomGlobalSettingResponse: ...


class SystemAPI(Protocol):
    async def get_bedrock_process_info(
        self, request: GetBedrockProcessInfoRequest | Mapping[str, object]
    ) -> GetBedrockProcessInfoResponse: ...

    async def get_server_running_status(
        self, request: GetServerRunningStatusRequest | Mapping[str, object]
    ) -> GetServerRunningStatusResponse: ...


class WebsocketAPI(Protocol):
    async def websocket_broadcast(
        self, request: BroadcastRequest | Mapping[str, object]
    ) -> BroadcastResponse: ...

    async def websocket_publish_ws_event(
        self, request: PublishWsEventRequest | Mapping[str, object]
    ) -> PublishWsEventResponse: ...

    async def websocket_send_to_client(
        self, request: SendToClientRequest | Mapping[str, object]
    ) -> SendToClientResponse: ...

    async def websocket_send_to_user(
        self, request: SendToUserRequest | Mapping[str, object]
    ) -> SendToUserResponse: ...

    async def websocket_unregister_data_provider(
        self, request: UnregisterDataProviderRequest | Mapping[str, object]
    ) -> UnregisterDataProviderResponse: ...


class WorldAPI(Protocol):
    async def export_world(
        self, request: ExportWorldRequest | Mapping[str, object]
    ) -> ExportWorldResponse: ...

    async def get_world_name(
        self, request: GetWorldNameRequest | Mapping[str, object]
    ) -> GetWorldNameResponse: ...

    async def import_world(
        self, request: ImportWorldRequest | Mapping[str, object]
    ) -> ImportWorldResponse: ...


class RuntimeAPI(Protocol):
    async def run_task(
        self,
        target_function: Callable[..., Any],
        *args: Any,
        username: str | None = None,
        **kwargs: Any,
    ) -> str: ...

    def server_lifecycle_manager(
        self,
        server_name: str,
        stop_before: bool,
        start_after: bool = True,
        restart_on_success_only: bool = False,
    ) -> AsyncContextManager[None]: ...

    async def register_data_provider(
        self, topic: str, handler: Callable[..., Any]
    ) -> None: ...


API_METHODS: dict[str, dict[str, str]] = {
    "addon": {
        "disable_addon": "disable_addon",
        "enable_addon": "enable_addon",
        "import_addon": "import_addon",
        "list_available_addons": "list_available_addons",
        "list_installed_addons": "list_installed_addons",
        "reorder_addons": "reorder_addons",
    },
    "allowlist": {
        "add_to_allowlist": "add_to_allowlist",
        "get_allowlist": "get_allowlist",
        "remove_from_allowlist": "remove_from_allowlist",
    },
    "application": {
        "get_all_servers_data": "get_all_servers_data",
        "get_system_and_app_info": "get_system_and_app_info",
        "list_available_worlds": "list_available_worlds",
        "update_server_statuses": "update_server_statuses",
    },
    "backup_restore": {
        "backup_all": "backup_all",
        "backup_config_file": "backup_config_file",
        "backup_world": "backup_world",
        "list_backup_files": "list_backup_files",
        "prune_old_backups": "prune_old_backups",
        "restore_all": "restore_all",
        "restore_config_file": "restore_config_file",
        "restore_world": "restore_world",
    },
    "ban": {"add_server_ban": "add_server_ban", "get_server_bans": "get_server_bans"},
    "install": {
        "install_new_server": "install_new_server",
        "update_server": "update_server",
    },
    "misc": {"prune_download_cache": "prune_download_cache"},
    "permissions": {
        "get_permissions": "get_permissions",
        "set_permissions": "set_permissions",
    },
    "player": {
        "add_players_manually": "add_players_manually",
        "get_all_known_players": "get_all_known_players",
        "scan_and_update_player_db": "scan_and_update_player_db",
    },
    "plugins": {
        "get_plugin_setting": "get_plugin_setting",
        "get_plugin_statuses": "get_plugin_statuses",
        "reload_plugin": "reload_plugin",
        "set_plugin_setting": "set_plugin_setting",
    },
    "properties": {
        "get_properties": "get_properties",
        "set_properties": "set_properties",
        "validate_property_value": "validate_property_value",
    },
    "server": {
        "get_all_settings": "get_all_server_settings",
        "get_setting": "get_server_setting",
        "get_summary": "get_server_summary",
        "restart": "restart_server",
        "send_command": "send_command",
        "set_custom_value": "set_server_custom_value",
        "set_status": "set_server_status",
        "start": "start_server",
        "stop": "stop_server",
        "update_player_stats": "update_server_player_stats",
    },
    "settings": {
        "get_all_global_settings": "get_all_global_settings",
        "get_global_setting": "get_global_setting",
        "set_custom_global_setting": "set_custom_global_setting",
    },
    "system": {
        "get_bedrock_process_info": "get_bedrock_process_info",
        "get_server_running_status": "get_server_running_status",
    },
    "websocket": {
        "websocket_broadcast": "websocket_broadcast",
        "websocket_publish_ws_event": "websocket_publish_ws_event",
        "websocket_send_to_client": "websocket_send_to_client",
        "websocket_send_to_user": "websocket_send_to_user",
        "websocket_unregister_data_provider": "websocket_unregister_data_provider",
    },
    "world": {
        "export_world": "export_world",
        "get_world_name": "get_world_name",
        "import_world": "import_world",
    },
}
