# bedrock_server_manager/web/routers/register.py
"""
FastAPI router for user registration management.

This module provides endpoints for:
- Generating registration tokens (Admin only).
- Serving the registration page.
- Handling user registration submissions.
"""

import logging
import secrets
import time

from fastapi import APIRouter, Depends, HTTPException, Request, status
from fastapi.responses import JSONResponse
from sqlalchemy.exc import IntegrityError

from ...context import AppContext
from ...utils import get_password_hash
from ..deps import get_admin_user, get_app_context
from ..schemas import ActionResponse, GenerateTokenPayload, UserLoginPayload
from ..schemas import UserResponse as UserSchema

logger = logging.getLogger(__name__)

router = APIRouter(
    prefix="/api/register",
    tags=["Registration", "User Management"],
)


@router.post(
    "/generate-token",
    response_model=ActionResponse,
)
async def generate_token(
    request: Request,
    data: GenerateTokenPayload,
    current_user: UserSchema = Depends(get_admin_user),
    app_context: AppContext = Depends(get_app_context),
):
    """
    Generates a new registration token.
    """

    token = secrets.token_urlsafe(32)
    expires = int(time.time()) + 86400  # 24 hours
    async with app_context.storage.transaction() as session:
        await app_context.storage.user_repo.create_registration_token(
            session, token=token, role=data.role, expires=expires
        )

    base_url = str(request.base_url)
    registration_link = f"{base_url}app/register/{token}"

    logger.info(
        f"Registration token for role '{data.role}' generated by '{current_user.username}'. "
        f"Link: {registration_link}"
    )

    return ActionResponse(
        status="success",
        message="Token generated successfully.",
        registration_url=registration_link,
    )


@router.get(
    "/validate/{token}",
)
async def validate_token(
    token: str,
    app_context: AppContext = Depends(get_app_context),
):
    """
    Checks if a registration token is valid.
    """
    async with app_context.storage.transaction() as session:
        registration_token = await app_context.storage.user_repo.get_registration_token(
            session, token
        )
        if not registration_token or registration_token.expires < int(time.time()):
            return JSONResponse(
                content={"status": "error", "message": "Invalid or expired token."},
                status_code=status.HTTP_404_NOT_FOUND,
            )

        return JSONResponse(
            content={"status": "success", "message": "TokenResponse is valid."}
        )


@router.post(
    "/{token}",
)
async def register_user(
    token: str,
    data: UserLoginPayload,
    app_context: AppContext = Depends(get_app_context),
):
    """
    Creates a new user from a registration token.
    """
    async with app_context.storage.transaction() as session:
        registration_token = await app_context.storage.user_repo.get_registration_token(
            session, token
        )
        if not registration_token or registration_token.expires < int(time.time()):
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail={
                    "status": "error",
                    "message": "Invalid or expired registration token.",
                },
            )

        hashed_password = get_password_hash(data.password)

        try:
            await app_context.storage.user_repo.create_user(
                session,
                username=data.username,
                hashed_password=hashed_password,
                role=str(registration_token.role),
            )
            await app_context.storage.user_repo.delete_registration_token(
                session, registration_token
            )
            await session.commit()

            logger.info(
                f"UserResponse '{data.username}' registered with role '{registration_token.role}'."
            )

            return JSONResponse(
                content={
                    "status": "success",
                    "message": "Registration successful. Please log in.",
                },
                status_code=status.HTTP_200_OK,
            )

        except IntegrityError:
            await session.rollback()
            logger.warning(
                f"Registration failed: Username '{data.username}' already exists."
            )
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail={
                    "status": "error",
                    "message": "Username already exists. Please choose a different one.",
                },
            )
        except Exception as e:
            await session.rollback()
            logger.error(
                f"An unexpected error occurred during registration: {e}", exc_info=True
            )
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail={
                    "status": "error",
                    "message": "An unexpected server error occurred during registration.",
                },
            )
