# bedrock_server_manager/web/routers/register.py
"""
FastAPI router for user registration management.

This module provides endpoints for:
- Generating registration tokens (Admin only).
- Serving the registration page.
- Handling user registration submissions.
"""

import logging
import secrets
import time

from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi.responses import JSONResponse

from ...context import AppContext
from ...utils import get_password_hash
from ..deps import get_admin_user, get_app_context
from ..schemas import GenerateTokenPayload, UserLoginPayload
from ..schemas import UserResponse as UserSchema
from ..schemas.base import RegistrationResponse

logger = logging.getLogger(__name__)

router = APIRouter(
    prefix="/api/register",
    tags=["Registration", "User Management"],
)


@router.post(
    "/generate-token",
    operation_id="generate_registration_token",
    response_model=RegistrationResponse,
)
async def generate_token(
    request: Request,
    data: GenerateTokenPayload,
    current_user: UserSchema = Depends(get_admin_user),
    app_context: AppContext = Depends(get_app_context),
) -> RegistrationResponse:
    """
    Generates a new registration token.
    """

    token = secrets.token_urlsafe(32)
    expires = int(time.time()) + 86400  # 24 hours
    async with app_context.storage.transaction() as session:
        await app_context.storage.user_repo.create_registration_token(
            session, token=token, role=data.role, expires=expires
        )

    base_url = str(request.base_url)
    registration_link = f"{base_url}app/register/{token}"

    logger.info(
        f"Registration token for role '{data.role}' generated by '{current_user.username}'. "
        f"Link: {registration_link}"
    )

    return RegistrationResponse(
        status="success",
        message="Token generated successfully.",
        registration_url=registration_link,
    )


@router.get(
    "/validate/{token}",
    operation_id="validate_registration_token",
)
async def validate_token(
    token: str,
    app_context: AppContext = Depends(get_app_context),
):
    """
    Checks if a registration token is valid.
    """
    async with app_context.storage.transaction() as session:
        registration_token = await app_context.storage.user_repo.get_registration_token(
            session, token
        )
        if (
            not registration_token
            or registration_token.expires is None
            or registration_token.expires < int(time.time())
        ):
            raise HTTPException(status_code=404, detail="Invalid or expired token.")

        return JSONResponse(
            content={"status": "success", "message": "TokenResponse is valid."}
        )


@router.post(
    "/{token}",
    operation_id="register_user",
)
async def register_user(
    token: str,
    data: UserLoginPayload,
    app_context: AppContext = Depends(get_app_context),
):
    """
    Creates a new user from a registration token.
    """
    record = await app_context.user_service.create_account(
        data.username, get_password_hash(data.password), token=token
    )
    if record is None:
        raise HTTPException(
            status_code=404, detail="Invalid or expired registration token."
        )
    return JSONResponse(
        content={
            "status": "success",
            "message": "Registration successful. Please log in.",
        }
    )
