"""Generate typed plugin namespaces from registered API contracts; use --check in CI."""

import argparse
import inspect
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from bedrock_server_manager.plugins.api_bridge import _api_registry  # noqa: E402
from bedrock_server_manager.plugins.api_contract import get_contract  # noqa: E402


def method_name(domain, name):
    if domain == "server":
        return name.replace("server_", "").replace("_server", "")
    return name


def generate():
    imports = set()
    mapping = {}
    classes = []
    for domain in sorted({item[4] for item in _api_registry.values()}):
        methods = []
        names = {}
        for name, (func, exposed, _, _, owner) in sorted(_api_registry.items()):
            if owner != domain:
                continue
            contract = get_contract(func)
            if contract is None:
                continue
            request, response = contract
            imports.update((request.__name__, response.__name__))
            method = method_name(domain, name)
            if method in names:
                raise ValueError(f"Duplicate plugin method: {domain}.{method}")
            names[method] = name
            prefix = "async " if inspect.iscoroutinefunction(func) else ""
            methods.append(
                f"    {prefix}def {method}(self, request: {request.__name__} | Mapping[str, object]) -> {response.__name__}: ..."
            )
        mapping[domain] = names
        classes.append(
            f"class {domain.title().replace('_', '')}API(Protocol):\n"
            + "\n\n".join(methods)
            + "\n"
        )
    content = (
        '"""Generated by scripts/generate_plugin_api.py; do not edit manually."""\n'
        "from typing import Any, AsyncContextManager, Callable, Mapping, Protocol\n"
        "from bedrock_server_manager.api.models import (\n"
        + "".join(f"    {name},\n" for name in sorted(imports))
        + ")\n\n"
        + "\n".join(classes)
        + "\n"
        + """class RuntimeAPI(Protocol):
    async def run_task(self, target_function: Callable[..., Any], *args: Any, username: str | None = None, **kwargs: Any) -> str: ...

    def server_lifecycle_manager(self, server_name: str, stop_before: bool, start_after: bool = True, restart_on_success_only: bool = False) -> AsyncContextManager[None]: ...

    async def register_data_provider(self, topic: str, handler: Callable[..., Any]) -> None: ...

"""
        + "API_METHODS: dict[str, dict[str, str]] = "
        + repr(mapping)
        + "\n"
    )
    return content, mapping


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content, _ = generate()
    # Format deterministically using the project's tools.
    import black
    import isort

    content = black.format_str(
        isort.code(content, profile="black"),
        mode=black.Mode(
            target_versions={
                black.TargetVersion.PY311,
                black.TargetVersion.PY312,
                black.TargetVersion.PY313,
                black.TargetVersion.PY314,
            }
        ),
    )
    path = ROOT / "src/bedrock_server_manager/plugins/api_types.py"
    if args.check:
        if not path.exists() or path.read_text() != content:
            sys.exit("Plugin API types are stale; run scripts/generate_plugin_api.py")
    else:
        path.write_text(content)
