name: Bedrock Server Manager - Upload Artifacts

on:
  push:
    paths:
      - 'bedrock_server_manager/**'
      - '.test/**'
  pull_request:
    paths:
      - 'bedrock_server_manager/**'
      - '.test/**'

jobs:

  script-checks:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Create virtual environment
      run: python -m venv .venv

    - name: Activate virtual environment
      shell: bash
      run: source .venv/bin/activate

    - name: Install dependencies
      shell: bash
      run: |
        source .venv/bin/activate
        pip install -U pip
        pip install .

    - name: Install linting and testing tools (flake8)
      shell: bash
      run: |
        source .venv/bin/activate
        pip install flake8

    - name: Get current version from pyproject.toml
      id: get_current_version
      shell: bash
      run: |
        CURRENT_VERSION=$(grep '^version = "' pyproject.toml | cut -d '"' -f 2)
        if [[ -z "$CURRENT_VERSION" ]]; then
          echo "::warning::Could not find version in pyproject.toml. Using default version 0.0.0."
          CURRENT_VERSION="0.0.0"
        fi
        echo "::set-output name=version::${CURRENT_VERSION}"

    - name: Get Short SHA (using shell) 
      id: short_sha
      shell: bash
      run: |
        echo "::set-output name=sha_short::$(echo ${{ github.sha }} | cut -c 1-7)"

    - name: Build package
      shell: bash
      run: |
        source .venv/bin/activate
        pip install build
        python -m build

    - name: Upload distribution packages as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bedrock-server-manager.${{ steps.short_sha.outputs.sha_short }}
        path: dist/

    - name: Lint with flake8
      shell: bash
      run: |
        source .venv/bin/activate
        flake8 bedrock_server_manager --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 bedrock_server_manager --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics