name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [refactor/docs]

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install project dependencies including docs extra
      run: pip install .[docs]

    - name: Build and deploy Sphinx documentation
      id: deployment
      uses: sphinx-notes/pages@v3
      with:
        documentation_path: ./docs
        pyproject_extras: docs 

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
