# .github/workflows/publish-to-pypi.yml

name: Publish Python Package using OIDC

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/bedrock-server-manager

    permissions:
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: python -m pip install --upgrade pip build

      - name: Build package
        run: python -m build

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: Publish package distributions to PyPI
        if: github.event.release.prerelease == false
        uses: pypa/gh-action-pypi-publish@release/v1